/* eslint-disable react/prop-types */
import 'src/styles/globals.css';

import { Geist, Geist_Mono } from 'next/font/google';
import Head from 'next/head';
import { Header } from 'src/components/Header';
import { useCounter } from 'src/hooks/useCounter';
import { useInput } from 'src/hooks/useInput';
import { useSetBgColor } from 'src/hooks/useSetBgColor';
import styles from 'src/styles/Home.module.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const App = ({ Component, pageProps }) => {
  const counter = useCounter();
  const input = useInput();
  useSetBgColor();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <Component {...pageProps} {...counter} {...input} />
      </div>
    </>
  );
};

export default App;
