import { Geist, Geist_Mono } from 'next/font/google';
import Head from 'next/head';
import Footer from 'src/components/Footer/Footer';
import Header from 'src/components/Header/Header';
import Main from 'src/components/Main/Main';
import styles from 'src/styles/Home.module.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />
        <Main title="index" />
        <Footer />
      </div>
    </>
  );
}
